"""RAG Copy Generation Agent.

Per ADR-002: copy is grounded in two RAG sources, brand_voice.md and
product_fact_sheet.md. Brand voice plays a dual role:

  1. As a retrieval source. Sections (anchored by `§N`) are indexed and
     retrieved alongside fact-sheet chunks. Citations to brand-voice rules
     emit anchors like `[brand_voice:§3]`.

  2. As a system-prompt style guide. A short, deterministic summary of the
     voice doc (tone, prohibited language, principles 1-7) is rendered into
     the LLM system prompt at every generation. This biases default style
     even when retrieval surfaces no specific voice paragraph.

The two roles are complementary, not redundant. Retrieval-only handling
leaves a default-style gap on prompts that don't pull voice context;
system-prompt-only handling has no citation trail. Combining the two keeps
citations auditable while ensuring brand-aligned default tone.

Output contract: every factual claim about price, allowance, restriction,
or eligibility must cite a `[fact_sheet:<sku>:<field>]` anchor. Stylistic
or framing claims that follow a brand-voice rule must cite `[brand_voice:§N]`.
The deterministic citation check in the Legal/Brand Review Gate (ADR-003)
is the release-time enforcement; this agent prompts for citations but does
not gate.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import faiss
import numpy as np

from brandguard.llm import LLMCall, default_complete

DATA_DIR = Path(__file__).resolve().parents[3] / "data"
BRAND_VOICE_PATH = DATA_DIR / "brand_voice.md"
FACT_SHEET_PATH = DATA_DIR / "product_fact_sheet.md"


@dataclass
class Chunk:
    anchor: str
    source: str  # "brand_voice" or "fact_sheet"
    text: str


# A regex that matches the §N section headers in brand_voice.md.
# Headers in our doc look like: `## §1. Brand Name`
_BRAND_VOICE_HEADER = re.compile(r"^##\s+§(\d+)\.\s+(.+?)$", re.MULTILINE)
# Fact-sheet anchor lines look like: `- **\`[fact_sheet:essentials:price]\`** ...`
_FACT_ANCHOR = re.compile(r"\[fact_sheet:([a-z_+]+):([a-z_+]+)\]")


def chunk_brand_voice(text: str) -> list[Chunk]:
    """Split brand_voice.md into one chunk per `§N` section."""
    matches = list(_BRAND_VOICE_HEADER.finditer(text))
    chunks: list[Chunk] = []
    for i, m in enumerate(matches):
        section_num = m.group(1)
        section_title = m.group(2).strip()
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        anchor = f"[brand_voice:§{section_num}]"
        chunks.append(
            Chunk(anchor=anchor, source="brand_voice", text=f"{section_title}\n{body}")
        )
    return chunks


def chunk_fact_sheet(text: str) -> list[Chunk]:
    """Split product_fact_sheet.md into one chunk per `[fact_sheet:<sku>:<field>]` line."""
    chunks: list[Chunk] = []
    for line in text.splitlines():
        m = _FACT_ANCHOR.search(line)
        if not m:
            continue
        sku, field = m.group(1), m.group(2)
        anchor = f"[fact_sheet:{sku}:{field}]"
        chunks.append(Chunk(anchor=anchor, source="fact_sheet", text=line.strip()))
    return chunks


def build_corpus_chunks(
    brand_voice_path: Path = BRAND_VOICE_PATH,
    fact_sheet_path: Path = FACT_SHEET_PATH,
) -> list[Chunk]:
    bv = brand_voice_path.read_text(encoding="utf-8")
    fs = fact_sheet_path.read_text(encoding="utf-8")
    return chunk_brand_voice(bv) + chunk_fact_sheet(fs)


def collect_known_anchors(
    brand_voice_path: Path = BRAND_VOICE_PATH,
    fact_sheet_path: Path = FACT_SHEET_PATH,
) -> set[str]:
    """Return the set of every citation anchor that exists in the RAG sources."""
    return {c.anchor for c in build_corpus_chunks(brand_voice_path, fact_sheet_path)}


def build_brand_voice_summary(brand_voice_path: Path = BRAND_VOICE_PATH) -> str:
    """Deterministic summary of brand_voice.md for the system prompt.

    Pulls the §3 personality bullets and §4 voice principles by section header.
    The summary is generated by template fill, not by an LLM, so it never drifts
    from the doc.
    """
    text = brand_voice_path.read_text(encoding="utf-8")
    sections = list(_BRAND_VOICE_HEADER.finditer(text))
    summary_lines = ["Strand Wireless brand voice (system-prompt floor):"]
    for i, m in enumerate(sections):
        num, title = m.group(1), m.group(2).strip()
        if num in {"3", "4"}:
            start = m.end()
            end = sections[i + 1].start() if i + 1 < len(sections) else len(text)
            body = text[start:end].strip()
            summary_lines.append(f"§{num} {title}:")
            summary_lines.append(body)
    return "\n\n".join(summary_lines)


# ----- Embedding + FAISS index -----

_EMBEDDING_MODEL = None


def _get_embedding_model():
    global _EMBEDDING_MODEL
    if _EMBEDDING_MODEL is None:
        from fastembed import TextEmbedding

        _EMBEDDING_MODEL = TextEmbedding(model_name="BAAI/bge-small-en-v1.5")
    return _EMBEDDING_MODEL


def _embed(texts: list[str]) -> np.ndarray:
    model = _get_embedding_model()
    vectors = np.array(list(model.embed(texts)), dtype="float32")
    return vectors


@dataclass
class FaissIndex:
    chunks: list[Chunk]
    index: Any
    dim: int


def build_index(chunks: list[Chunk] | None = None) -> FaissIndex:
    if chunks is None:
        chunks = build_corpus_chunks()
    vectors = _embed([c.text for c in chunks])
    dim = vectors.shape[1]
    index = faiss.IndexFlatIP(dim)
    faiss.normalize_L2(vectors)
    index.add(vectors)
    return FaissIndex(chunks=chunks, index=index, dim=dim)


def retrieve(faiss_index: FaissIndex, query: str, top_k: int = 8) -> list[Chunk]:
    vectors = _embed([query])
    faiss.normalize_L2(vectors)
    _scores, idxs = faiss_index.index.search(vectors, top_k)
    return [faiss_index.chunks[i] for i in idxs[0] if 0 <= i < len(faiss_index.chunks)]


# ----- Generation -----


GENERATION_SYSTEM = """You are the Strand Wireless copy generator.

You write campaign copy grounded in retrieved chunks. Every factual claim
about price, data allowance, network type, hotspot, streaming, international,
restriction, or eligibility must end with a citation anchor pulled VERBATIM
from the retrieved chunks. Stylistic or framing claims that follow a brand
voice rule should cite the matching `[brand_voice:§N]` anchor.

Anchor format examples:
  - [fact_sheet:pro:price]
  - [fact_sheet:unlimited_plus:data]
  - [brand_voice:§4]

Do not invent anchors. If a claim cannot be supported by the retrieved
chunks, omit the claim. The output is reviewed by a deterministic gate:
unsupported anchors block release.

Brand voice rules apply to every output (see system-prompt floor below).
Use plain English. No filler intensifiers. Numbers and disclosures must be
explicit. The word `unlimited` may only appear when paired with the soft cap
and post-cap speed in the same sentence.

{brand_voice_summary}

Format your reply as:

COPY:
<the copy>

CITATIONS:
- <anchor 1>
- <anchor 2>
"""


def generate_copy(
    campaign_brief: str,
    audience_summary: str,
    faiss_index: FaissIndex | None = None,
    llm: LLMCall | None = None,
    top_k: int = 8,
) -> dict[str, Any]:
    """Retrieve chunks, generate copy, parse citations.

    Returns a dict with:
        copy: str
        citations: list[str]
        retrieved_anchors: list[str]
        raw: str
    """
    if faiss_index is None:
        faiss_index = build_index()
    if llm is None:
        llm = default_complete

    query = f"{campaign_brief}\nAudience: {audience_summary}"
    retrieved = retrieve(faiss_index, query, top_k=top_k)

    retrieved_block = "\n\n".join(f"{c.anchor}\n{c.text}" for c in retrieved)
    user_prompt = (
        f"Audience summary:\n{audience_summary}\n\n"
        f"Campaign brief:\n{campaign_brief}\n\n"
        f"Retrieved chunks:\n{retrieved_block}\n\n"
        "Write campaign copy that respects the brand voice rules and cites every "
        "factual claim with an anchor from the retrieved chunks above."
    )
    system_prompt = GENERATION_SYSTEM.format(
        brand_voice_summary=build_brand_voice_summary()
    )

    raw = llm(system_prompt, user_prompt, 1024)
    copy_text, citations = _parse_generation(raw)

    return {
        "copy": copy_text,
        "citations": citations,
        "retrieved_anchors": [c.anchor for c in retrieved],
        "raw": raw,
    }


def _parse_generation(raw: str) -> tuple[str, list[str]]:
    """Split the model output into copy and an explicit citation list."""
    copy_match = re.search(r"COPY:\s*(.+?)(?:\n\s*CITATIONS:|$)", raw, re.DOTALL)
    copy_text = copy_match.group(1).strip() if copy_match else raw.strip()

    citations_match = re.search(r"CITATIONS:\s*(.+)$", raw, re.DOTALL)
    citations: list[str] = []
    if citations_match:
        for line in citations_match.group(1).splitlines():
            line = line.strip().lstrip("-").strip()
            if not line:
                continue
            for anchor in re.findall(r"\[(?:brand_voice|fact_sheet):[^\]]+\]", line):
                citations.append(anchor)

    # Also pull inline anchors from the copy text itself in case the model emitted
    # anchors only in COPY and not in CITATIONS.
    inline = re.findall(r"\[(?:brand_voice|fact_sheet):[^\]]+\]", copy_text)
    for anchor in inline:
        if anchor not in citations:
            citations.append(anchor)

    return copy_text, citations
